CREATE TABLE USERS(
USER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
EMAIL VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(30)
);

CREATE TABLE EVENTS(
EVENT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
FK_ORGANIZER_ID BIGINT,
  CONSTRAINT FK_EVENT_TO_ORGANIZER FOREIGN KEY (FK_ORGANIZER_ID)
    REFERENCES ORGANIZERS(ORGANIZER_ID)
);

CREATE TABLE USERS_TO_EVENTS(
USER_TO_EVENT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
FK_USER_ID BIGINT NOT NULL,
FK_EVENT_ID BIGINT NOT NULL,
  CONSTRAINT FK_UTE_TO_USERS FOREIGN KEY (FK_USER_ID)
    REFERENCES USERS (USER_ID),
  CONSTRAINT FK_UTE_TO_EVENTS FOREIGN KEY (FK_EVENT_ID)
    REFERENCES EVENTS (EVENT_ID),
USER_STATUS VARCHAR(20) NOT NULL DEFAULT 'INVITED'
);

CREATE TABLE ORGANIZERS(
ORGANIZER_ID BIGINT PRIMARY KEY NOT NULL,
  CONSTRAINT FK_USER_ID FOREIGN KEY (ORGANIZER_ID)
    REFERENCES USERS(USER_ID)
);

