CREATE TABLE USERS(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
EMAIL VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(30)
);

CREATE TABLE EVENTS(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
FK_ORGANIZER_ID BIGINT,
  CONSTRAINT FK_EVENT_TO_ORGANIZER FOREIGN KEY (FK_ORGANIZER_ID)
    REFERENCES ORGANIZERS(ID)
);

CREATE TABLE USERS_TO_EVENTS(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
FK_USER_ID BIGINT NOT NULL,
FK_EVENT_ID BIGINT NOT NULL,
  CONSTRAINT FK_UTE_TO_USERS FOREIGN KEY (FK_USER_ID)
    REFERENCES USERS (ID),
  CONSTRAINT FK_UTE_TO_EVENTS FOREIGN KEY (FK_EVENT_ID)
    REFERENCES EVENTS (ID),
USER_STATUS VARCHAR(20) NOT NULL DEFAULT 'INVITED'
);

CREATE TABLE ORGANIZERS(
ID BIGINT PRIMARY KEY NOT NULL,
  CONSTRAINT FK_USER_ID FOREIGN KEY (ID)
    REFERENCES USERS(ID)
);

