CREATE TABLE USERS(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
EMAIL VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(30)
);

CREATE TABLE EVENTS(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL
);

CREATE TABLE USERS_TO_EVENTS(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
FK_USER_ID BIGINT NOT NULL,
FK_EVENT_ID BIGINT NOT NULL,
  CONSTRAINT FK_UTE_TO_USERS FOREIGN KEY (FK_USER_ID)
    REFERENCES USERS (ID),
  CONSTRAINT FK_UTE_TO_EVENTS FOREIGN KEY (FK_EVENT_ID)
    REFERENCES EVENTS (ID)
);
